name: Defectdojo - endorlabs

on:
  push:
    branches:
      - "main"

jobs:
  endorlabs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - name: install endorctl
        run: | 
          npm install -g endorctl
