name: ci.yml
on: [pull_request, push, workflow_dispatch]

jobs:
  SCA:
    name: SCA
    runs-on: ubuntu-latest
    container:
      image: naveen2131/my-app:baseimage
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2 

      - name: Check Quality Gates
        run: |
          riskScore=$(curl -s -X GET -H "X-Api-Key: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}" \
            "https://uat-sca.m2pfintech.com/api/v1/project/acs-backend/current-state" | \
            jq -r '.metrics.riskScore')

          echo "Dependency-Track Risk Score: $riskScore"

          if [ $riskScore -ge 1 ]; then
            echo "Low risk detected. Failing the workflow."
            exit 1
          else
            echo "No Low risk detected."
          fi
