name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2

jobs:
  build:
    name: Build and SBOM Generation
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate SBOM
        run: |
          npm install -g @cyclonedx/cdxgen@8.5.0
          cdxgen -r -o sbom.xml
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom-artifact  
          path: sbom.xml      





      
