name: DefectDojo - Gitleaks
on: [pull_request, push, workflow_dispatch]

jobs:
  gitleaks_scan:
    name: Gitleaks Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        id: gitleaks
        uses: gitleaks/gitleaks-action@v2.3.2
        with:
          flags: "--all"
          output-format: "json"
