name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2

jobs:
  build:
    name: Build and SBOM Generation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"  
          cache: npm

      - run: java -version

      - name: Install npm dependencies
        run: npm install prismjs

      - name: Build
        run: npm run build

      - name: Run unit tests
        run: npm run test:unit

      - name: Generate SBOM
        run: |
          npm install -g cyclonedx-bom
          cyclonedx-bom -o sbom.xml

      - name: Upload SBOM to Dependency-Track
        env:
          DEPENDENCY_TRACK_API_KEY: LlhGj7VDHYtjUbhxh0caLaI4dff2W6wF 
        run: |
          curl -X POST -F "file=@sbom.xml" -H "Authorization: $DEPENDENCY_TRACK_API_KEY" https://20.233.94.210/api/v1/scan
