name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build and SBOM Generation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate SBOM
        run: |
          npm install -g @cyclonedx/cdxgen@8.5.0
          cdxgen -r -o sbom.xml

      - name: Upload SBOM to Dependency-Track
        run: |
          curl -X POST -F "file=@./sbom.xml" -H "Authorization: LlhGj7VDHYtjUbhxh0caLaI4dff2W6wF " http://20.233.94.210/api/v1/scan

