name: DefectDojo - Gitleaks
on: [pull_request, push, workflow_dispatch]

jobs:
  gitleaks_scan:
    name: Gitleaks Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: DariuszPorowski/github-action-gitleaks@v2
        with:
          fail: false
          flags: "--all"
          output-format: json

      - name: Upload Gitleaks Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: gitleaks-report
          path: gitleaks-report.json
