name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: npm

      - name: Install Sonar Scanner
        run: npm install -g sonar-scanner

      - name: SonarQube Scan
        run: |
          sonar-scanner -X \
            -Dsonar.projectKey=nodejs.org \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://20.203.85.49:9000/ \
            -Dsonar.login=58f2b5a42d009e5dec0b78a2ebc1ec41c4cc1061

      - name: Check SonarQube Quality Gate
        id: sonarqube-quality-gate
        run: |
          QUALITY_GATE_STATUS=$(curl -s "http://20.203.85.49:9000/api/qualitygates/project_status?projectKey=nodejs.org" -u "58f2b5a42d009e5dec0b78a2ebc1ec41c4cc1061:")
          echo "$QUALITY_GATE_STATUS"

          if [[ "$QUALITY_GATE_STATUS" == *"\"status\":\"ERROR\""* ]]; then
            echo "SonarQube Quality Gate check failed."
            echo "::set-output name=quality_gate_status::failed"
          else
            echo "SonarQube Quality Gate check passed."
            echo "::set-output name=quality_gate_status::passed"
          fi

      - name: Set Workflow Status
        run: |
          echo "Quality Gate Status: ${{ steps.sonarqube-quality-gate.outputs.quality_gate_status }}"
          if [[ "${{ steps.sonarqube-quality-gate.outputs.quality_gate_status }}" == "failed" ]]; then
            echo "Setting workflow status to failed."
            exit 1
          fi
