name: CI

on:
  push:
    branches:
      - main
  pull_request:
    workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Lint
        run: |
          echo "::add-matcher::.github/workflows/remark-lint-problem-matcher.json"
          npm run test:lint

  test:
    name: Node on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: npm

      - run: java -version

      - name: Install npm dependencies
        run: npm ci

      - name: Build
        run: npm run build

  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: npm

      - name: Trigger SonarQube Analysis
        run: |
          SONARQUBE_WEBHOOK_URL="http://20.203.85.49:9000/api/webhooks/2K7Wdpe4vbiHvxrssFOrjPS9Nfg2M91fknsuWQ+15mk="
          curl -X POST $SONARQUBE_WEBHOOK_URL
